export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_SET_CURRENT_USER = "AUTH_SET_CURRENT_USER";
export const AUTH_GET_CURRENT_USER = "AUTH_GET_CURRENT_USER";
